### ISSUE TITLE
Linux arm64 / aarch64 builds of contracts broken

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#1011]
It appears that linux arm64 / aarch64 builds of contracts fail with errors about relocations.

This is an example failing build:
> /usr/bin/ld: /home/runner/work/rs-soroban-sdk/rs-soroban-sdk/target/aarch64-unknown-linux-gnu/debug/deps/soroban_token_sdk.1c28rz4gpwkk2qll.rcgu.o: Relocations in generic ELF (EM: 183)
>           /usr/bin/ld: /home/runner/work/rs-soroban-sdk/rs-soroban-sdk/target/aarch64-unknown-linux-gnu/debug/deps/soroban_token_sdk.1c28rz4gpwkk2qll.rcgu.o: error adding symbols: file in wrong format

https://github.com/stellar/rs-soroban-sdk/actions/runs/5360474620/jobs/9725396502?pr=1009

It's unclear how long this has been broken because we are only just adding CI for a variety of operating systems now in #1009.

The impact of this is that anyone using Linux with arm64 / aarch64 will not be able to test contracts. They'll be able to build to wasm32, but not to the host architecture.

While Linux with arm64 / aarch64 is not common as a workstation configuration, it is common in Docker images because any macOS user who has an Apple Silicon chip will be running Linux with arm64 / aarch64 images by default.

**Comment by leighmcculloch** [comment]
It's possible that the recent addition of `ctor` in https://github.com/stellar/rs-soroban-sdk/pull/1008 is the cause.

**Comment by graydon** [comment]
This might or might-not block final -- depends on whether it's just preventing contract development (shouldn't block, not too many users are likely to use aarch64 hosts for testing) or whether it's preventing building and running core (should probably block, operators are fairly likely to deploy core on a graviton host)

**Comment by graydon** [comment]
An update on this:

  - Building for aarch64 _on aarch64 hosts_ does not show this problem, only when _crossing_ from x64-linux to aarch64-linux (as we do in CI). I think this means that the M1-mac-with-docker `soroban contract build` scenario will not be a problem.
  - It also only happens when you have `crate-type = ["cdylib"]` in your `Cargo.toml`. If you build with _no_ crate type, or with `crate-type = ["lib"]`, it builds native libraries fine (I think static libs / rlibs).

IOW I think this is just a bug in the way cargo invokes the target linker when cross-compiling cdylibs (by the look of it, I think it's actually accidentally invoking the host linker).

For the SDK's CI _specifically_ this does present a small bug to fix still. We have a bunch of crates (all of the test contracts) with `crate-type = ["cdylib"]` and if we remove that we stop getting `.wasm` files out of the `--target=wasm32-unknown-unknown` part of the build. We can get those `.wasm` files _back_ if we do that part of the build with `cargo rustc --target=wasm32-unknown-unknown --crate-type=cdylib` -- specify the crate type only when building wasm -- but that in turn fails because we have a crate type that's _not_ cdylib (the one that's proc-macro) so .. that breaks _that_.

I'll continue to tinker with this for a little bit, but at this point I don't think it's fatal or even ought to block a release.

**Comment by graydon** [comment]
Pretty sure this is https://github.com/rust-lang/cargo/issues/4133 -- I've posted an update to PR #1060
