### ISSUE TITLE
soroban-sdk: No versions found

### ISSUE THREAD

**Issue by nagashi** [stellar/rs-soroban-sdk#1107]
I'm running in a Mac Os environment using Rust 1.73.0 with Visual StudioCode.   Within the Cargo.toml file, I'm receiving the titled error "soroban-sdk: No versions found".  Additionally, I went out to crate.io and ran the command "cargo add soroban-sdk" in the project directory to no avail.  My toml entry is below:

[dependencies]
soroban-sdk = "20.0.0-rc2"

[dev_dependencies]
soroban-sdk = { version = "20.0.0-rc2", features = ["testutils"] }

**Comment by leighmcculloch** [comment]
Is this the error you're seeing in VSCode when viewing Cargo.toml?
<img width="592" alt="Screenshot 2023-10-06 at 9 26 22 AM" src="https://github.com/stellar/rs-soroban-sdk/assets/351529/8e9fc573-758e-4d97-a660-034216a06f74">

That error is being displayed because the VSCode crates.io plugin only shows a list of non-pre-release releases of crates. soroban-sdk has only pre-release versions and so that plugin isn't showing any versions to you.

`20.0.0-rc2` is a valid version of the crate though, and if you look at the URL below you'll see the version is indeed present:
- https://crates.io/crates/soroban-sdk/20.0.0-rc2

I don't see any issues using cargo add when I use that same command locally. Could you share output?

When you compile your project is it able to retrieve the soroban-sdk okay?

**Comment by nagashi** [comment]
First, the error occurred in VsCode, and 2nd, I could compile and run a test successfully.  Thanks for replying with an explanation.  I'll let you know if I run into any other issues.
