### ISSUE TITLE
Type: Binary: Move binary memcpy Env fns into the Binary type

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#247]
We should move the binary linear memory fns out of the Env type and into the Binary type, and structure them so they are seamless and hidden from the user other than via conversions through From/TryFrom.

- `binary_new_from_linear_memory` should become `Binary::from_slice(...)` and a `impl TryFrom<&[u8]> for Binary`.
   https://github.com/stellar/rs-stellar-contract-sdk/blob/43be468dc1fdac3537aa6dd04e63873c98a9d05f/sdk/src/env.rs#L145-L148
- `binary_copy_from_linear_memory ` should become `Binary::copy_from_slice(self, ...)`.
   https://github.com/stellar/rs-stellar-contract-sdk/blob/43be468dc1fdac3537aa6dd04e63873c98a9d05f/sdk/src/env.rs#L161-L177
- `binary_copy_to_linear_memory ` should become `Binary::copy_to_slice(self, ...)`.
   https://github.com/stellar/rs-stellar-contract-sdk/blob/43be468dc1fdac3537aa6dd04e63873c98a9d05f/sdk/src/env.rs#L150-L159

For fixed size `ArrayBinary` types it would also be ideal to offer `from_array` and `copy_to_array` fns, as well as conversion fns in both directions (`impl TryFrom<[u8; N]> for ArrayBinary<N>`, `impl TryFrom<ArrayBinary<N>> for [u8; N]` which is possible with arrays.

**Comment by leighmcculloch** [comment]
@jonjove @sisuresh Is it critical in your opinion that we get this functionality into the SDK for the August release? The functionality is mostly an optimization, however, I think you folks had issues where not having this exceeded limits in the VM. Does that mean this is a blocking issue?

**Comment by jonjove** [comment]
@leighmcculloch I recall trying to deploy a contract built as "target" (so it was quite large) when I was running into an issue with "target-tiny" and this was effectively impossible because right now producing a `Bytes` of length `l` has `O(l^2)` space and time complexity. I'm not personally blocked by this, but deploying a 50k contract might be a no-go right now.

When I say deploy in the above, I specifically mean create the contract from WASM in unit-tests or within another contract.
