### ISSUE TITLE
Section contractenvmetav0 not always emitted depending on profile

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#383]
It is emitted when building target. This is unchanged if I remove the calls to `wasm-opt`.

**Comment by leighmcculloch** [comment]
After reading https://github.com/rust-lang/rust/issues/56639, I now believe my summary above about nightly vs stable is incorrect.

The comment here is likely the issue:
>Long story short a custom section always goes into the current codegen unit, but if nothing else is referenced from the codegen unit then the custom section doesn't get included in the final output because the linker never looks at the codegen unit/object file.

Ref: https://github.com/rust-lang/rust/issues/56639#issuecomment-445924692

In the release profile we recommend, a single codegen unit is used:
```toml
codegen-units = 1
```
This means the custom section is preserved because the unit is always passed to the linker.

Given the custom section is never referenced right now, for anyone not using a single codegen unit it will be a bit random for if this issue occurs or not, because it really just depends how the Rust build system divides logic into codegen units.

There is a common in the linked issue about in what cases the custom section will be included:

> In which crate is the custom section defined? | Where is the function containing the section? | How is the function containing the custom section called? | Is it generated?
> -- | -- | -- | --
> External crate | Submodule | Not called | No
> External crate | Submodule | Indirectly | No
> External crate | Submodule | Directly | Yes
> External crate | In root | Not called | No
> External crate | In root | Indirectly | Yes
> External crate | In root | Directly | Yes
> Main crate | Any | Any | Yes

Ref: https://github.com/rust-lang/rust/issues/56639#issue-388956758

**Comment by jonjove** [comment]
Reopening this for the moment based on https://github.com/stellar/rs-soroban-sdk/pull/386#issuecomment-1201610591.

**Comment by leighmcculloch** [comment]
@jonjove It looks like the token contract is still using an old version of soroban-sdk-macros, so it doesn't have the fix that was committed in #386. However, even with the macros crate updated in the token contract it doesn't make a difference, it is still missing.
