### ISSUE TITLE
Type: Vec: Add contains, binary search, and index of fns

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#398]
### What problem does your feature solve?

`Vec` is missing functions from the `std::Vec` interface. This issue was prompted by a message explicitly asking about `contains`.

### What would you like to see?

Add some of these functions.

### What alternatives are there?

TODO

**Comment by leighmcculloch** [comment]
Adding `contains` and other similar functions requires additional host functions. I opened https://github.com/stellar/rs-soroban-env/issues/317 requesting this.

**Comment by leighmcculloch** [comment]
> Add some of these functions.

The Vec type will likely go through many iterations of improvement when it comes to functions, so let's scope this issue to offering the following functions that relate to `contains` and are likely to be served by the same underlying host fns:
- `contains` - boolean for whether the vec contains the value
- `binary_search` - Similar to `contains`, but assumes a sorted vec, and will also return the insert point if not found.
- `first_index_of` - There is no `std::vec::Vec` version of this. It is a common pattern to find the position of an item in a vec by using an iterator in the form `vec.iter().position(...)`. It is not efficient to use an iterator for this use case since it would move so much logic into the contract, so we should offer a similar function on `Vec` itself. In the SDK layer we can debate the use of the term index vs position. Imo position makes more sense in the context of an iterator, and a little less sense in the context of contiguous vector, but I don't think it would be harmful to go either way.
- `last_index_of` - Similar to above.

**Comment by leighmcculloch** [comment]
Blocked on https://github.com/stellar/rs-soroban-env/issues/317
