### ISSUE TITLE
Contract Spec: Add capability to record test cases and expected outcomes to spec

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#414]
We should explore adding test cases to the contract spec.

Each test case would specify:
- ledger entries
- inputs
- expected output or outcome

These would be encoded into a separate custom section that operates as an extension to the contract spec. The main motivation for making it a separate custom section is so that it could be removed from the wasm binary easily without specialized tooling.

Use cases:

- We could add the ability to the CLI to execute test cases in a wasm.

- We could add the ability to the CLI to generate / output human readable documentation from the wasm about the test cases.

- We could use this to test new versions of the host against a wide variety of deployed contracts.

- Other could use this to check that their own contract and contracts they depend on continue to function consistently with host upgrades.

- Others could use this to gain confidence about contracts they depend on, and to understand edge cases that might not otherwise be obvious.

Related discussion: https://discord.com/channels/897514728459468821/1007060872138592286/1007072592919789589

cc @graydon

**Comment by graydon** [comment]
We could do this but .. I think most contracts work on/with a variety of _other_ contracts and authorization state, such that the mock context you'd be setting up would be fairly extensive. I'm not opposed to experimenting! Just .. worried it's a lot of work and not sure it'd pay off or even entirely work. cc @brson wdyt?

**Comment by brson** [comment]
I apologize in advance that this is a spew of ideas.

A bunch of use cases here that might be served in different ways. The idea of automatically testing contracts, and testing them across runtime upgrades, is something I love, and can have a big bang-for-buck.

Embedding declarative unit tests as described in the op does sound pretty static and limited to me. e.g. one of the things I have found myself quickly wanting to do in tests is advance time across multiple transactions, not just set up a static ledger snapshot and make a single transaction against it. The declarative approach described in the op could need to grow a lot to cover relevant use-cases. It also presumably requires developers to buy into writing a special type of unit test, and that might be a hard sell for speculative benefits. It would be much desirable to leverage "normal" Rust unit tests if possible.

I am imagining some other approaches to testing the entire ecosystem across runtime upgrades, but they are pretty divergent from the original topic of embedding unit tests in the wasm.

On the topic of embedded unit tests, instead of having a declarative approach of defining inputs and outputs, one could also just let contracts define a "self-test" function that does whatever it wants; perhaps that self-test runs live on-chain (or on a forked chain just for testing).

As I reread the op, the idea of embedding metadata in the specs makes me think of theorem provers. Declaring preconditions, postconditions, and state invariants is in the spirit of "specs", and could be used by various tooling to drive the contracts in an adversarial way.

**Comment by leighmcculloch** [comment]
> one could also just let contracts define a "self-test" function that does whatever it wants

Interesting. This would be simple to develop for.

A downside is if someone without the original code was running the self test and saw a failure, they probably can't reason about why it failed. Which means that prior to a new release, we might not be able to learn much about how we've caused a failure, if that is a bug or not.
