### ISSUE TITLE
Allow the caller to choose the threshold for Accounts

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#476]
The threshold during account verification is set to medium, but the contract writer should be able to set this to a different threshold if they'd like.

**Comment by sisuresh** [comment]
Yeah I don't think this is required at the moment.

**Comment by jonjove** [comment]
I agree about deferring this, but disagree about closing the issue. Closed issues don't get revisited, but this probably should get done at some point. For more context about why I think this should get done eventually, read on.

I don't think your motivation analysis is quite right, and this is something that came up in the discussion of CAP-50. The issue with your analysis is that it specifically applies to the token contract, and in that context it is right (which is why auth is built around medium right now). But other contracts might have different requirements. For example, it's not unreasonable that someone creates a token [administrator contract](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md#admin-interface) that replicates the existing stellar requirements for allow trust, which is low threshold rather than medium. Or someone could create a smart wallet that grants veto power to high threshold signatures from some account. These use cases are completely reasonable, and suggest that threshold flexibility is relevant.

If I've convinced either @leighmcculloch or @sisuresh that this is relevant in the future, please reopen.

**Comment by leighmcculloch** [comment]
> The issue with your analysis is that it specifically applies to the token contract

My motivation for why medium is not because of what the account can affect on the Soroban side, but because of what it can affect on the Stellar side with wrapping and unwrapping. If the only affect possible is wrap/unwrap assets, which are payments, then medium feels appropriate.

I agree there's potential for Stellar accounts to be used for administration and other things like as you describe, but we don't know if that's what people will do or if people will adopt ed25519 identifiers for them. It's possible that Stellar accounts get primarily used by everyday consumers / users / wallet holders, while more administrative-like functionality takes a different form.

I think we should wait to open this issue until we see the need arise.
