### ISSUE TITLE
Revisit native testing story

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-soroban-sdk#528]
### What problem does your feature solve?

The story around native testing (eg. rust compiled to machine code) and WASM testing (eg. rust compiled to WASM and run via VM) is very confusing right now. `contractimport!` makes it very natural to work with the WASM, but then we lose the debugging advantages of native code. Related to https://github.com/stellar/soroban-examples/pull/89.

### What would you like to see?

We need to revisit this
- in terms of how contracts support the various modes. Should the native testing helpers be auto-generated as part of `contractimport!` or some other macro?
- in terms of how the modes do/don't combine. For example, when testing the liquidity pool example there are 3 instances of the token contract: one for each reserve asset and one for the pool share. Should all contracts be native? Should all be WASM? A mixture?

### What alternatives are there?

TODO

**Comment by graydon** [comment]
I don't really feel this is actionable and would like to close it, unless @leighmcculloch feels this earmarks important actual suggestions you want to pursue?

**Comment by leighmcculloch** [comment]
Agreed, and it is mostly not actionable due to issues in the Rust compiler, mostly because making contracts that are libraries causes LTO not to run during compile if that library is also going to be a contract.

If folks want to be able to do this, then we need to encourage folks to build their contracts in libraries only, and then have a second crate that imports the library and exports the contents as a cdylib. This seems like an annoying overhead for the average developer just getting going in their early days. 

If anything, this could be a docs / tutorial.
