### ISSUE TITLE
Auth: Rename types and functions

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#534]
I think we should revisit some of the names of things in the soroban-sdk-auth crate:

- `NonceAuth` -> `SignatureWithNonce` – The type embodies a nonce and a signature, so it would be clearer if we named it so.
- `NonceAuth::read_nonce` -> `nonce` – The read is superfluous.
- `NonceAuth::read_and_increment_nonce` -> `increment_nonce` – The `read_and` is superfluous.
- `NonceAuth::get_signature` -> `signature` – The `get_` is superfluous.

I also think we should remove the `&Env` args from the `read_nonce` and `read_and_increment_nonce` functions. The type can store the `Env`, and it simplifies the interface that the trait must provide. This would make most implementations likely a `(Env, Signature)`.

cc @sisuresh

**Comment by jonjove** [comment]
@leighmcculloch I generally agree, but I disagree about the `read_and` part. You can think of that as the analog to atomic functions like [fetch_add](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicI32.html#method.fetch_add). The key piece of information is that the returned value is from before the increment. We can change the name, but I think it's critical to emphasize that piece of information.

**Comment by sisuresh** [comment]
1. Removing the `Env` arg is a good idea. 
2. Changing `read_and_increment_nonce` - I don't feel strongly about this, but is there a cost to the `read_and`? I think it adds some clarity because the user needs to implement this trait. The documentation should be good enough for this, but a more descriptive name doesn't hurt.
3. Non-sequential nonces - That's an interesting point, but I'm not sure it makes sense in the context of the auth crate. Contracts have full access to their nonces, and can implement any special handling they want. I'm not opposed to the `consume_nonce` rename though to keep it more generic.

**Comment by sisuresh** [comment]
Closed by #597 (Nonce management was removed from the auth crate).
