### ISSUE TITLE
Discussion: preserving insertion order on Map

### ISSUE THREAD

**Issue by accordeiro** [stellar/rs-soroban-sdk#564]
While writing a few contributions to the SDK, it took me a while to wrap my head around a specific behavior: I've noticed our current `Map` implementation does not preserve insertion order. This means, on the following scenario:

```rust
let map1 = map![&env, (1, 10), (2, 20)];
let map2 = map![&env, (2, 20), (1, 10)];
```

Our current behavior is:

```rust
// current behavior
let k1 = map1.keys(); // [1, 2]
let k2 = map2.keys(); // [1, 2]
```

Whereas I would expect it to be:

```rust
// expected behavior
let k1 = map1.keys(); // [1, 2]
let k2 = map2.keys(); // [2, 1]
```

I'm entirely new to the Rust ecosystem and it looks like this is be the expected behavior for similar standard Rust data structures, but I wanted to point out that it is inconsistent with many mature and widely adopted languages (e.g. [Python [since v3.7]](https://mail.python.org/pipermail/python-dev/2017-December/151283.html), [Ruby [since v1.9]](https://www.igvita.com/2009/02/04/ruby-19-internals-ordered-hash/), [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared)) that **do** preserve insertion order on hash maps.

So my question is: if our goal is to make Soroban very accessible and easy to transition from other ecosystems, should we try and change this behavior? 

This also came in a discussion with @leighmcculloch – please add any additional background you might have here on this issue :)

**Comment by leighmcculloch** [comment]
I think for developers coming from many of these other ecosystems this is going to be surprising for them writing Soroban contracts, in the same way it is generally surprising for a developer when they start writing Go after having developed in Python, JavaScript, Ruby.

The issue @accordeiro raises is a developer experience issue.

There is another reason to prefer insertion ordered maps, but it is separate from developer experience. That other reason is the need to consistently implement ScVal sorting in all SDKs, which still seems like a difficult task. We've discussed this previously and at the time there was push back and we resolved to keep maps as they are.

@paulbellamy Would be interested to hear your thoughts on the developer experience component of this, and separately how practical it will be to implement ScVal sorting in the js-stellar-sdk and Go SDK.

@graydon @jonjove We've discussed insertion order maps in the past, but we didn't really discuss the developer experience motivation for doing it.

Regardless of whether we change anything, we should improve the inline documentation for the `Map` type to make the fact it is an ordered map, with ordering that is out-of-control of the developer, really clear.

**Comment by graydon** [comment]
Soroban's maps are ordered maps. Ordered maps order their input canonically, intentionally, both to support range queries and also (more importantly) to support an equality relation that is respected by most functions: if `a == b` for two maps `a` and `b` then `f(a) == f(b)` for any pure function `f`. This is especially important for serialization and hashing.

This is not true for unordered maps, in general, if they offer _any_ way of accessing the order (most do), because they almost always define equality pointwise: for maps `a` and `b`, `a == b` iff `(for (k, v) in a: b[k] == v) && (for (k,v in b: a[k] == v)`. Supporting more elaborate types of equality would likely confuse users (as it does in most languages that support it).

"Insertion-order preserving" is a thing people sometimes equip _unordered_ maps with. I'll admit it's an occasionally useful order to impose, and I think the ubiquitous hashtables in a lot of scripting languages have adopted it out of some mixture of "users find it helpful sometimes" and a desire for greater determinism (though it comes at some implementation cost, and there's usually a counterargument that unordered maps ought to lean into disorder and _randomize_ like they do in Rust and Go). But in any event the whole concept only applies to unordered maps, and does not solve the problem of supporting an equality relation on the maps, and is therefore (like unordered maps in general) IMO a huge footgun.

Try this in Python:

```
$ python3
Python 3.9.13 (main, May 24 2022, 21:28:31) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> x = dict(); x[1] = 'a'; x[2] = 'b';
>>> y = dict(); y[2] = 'b'; y[1] = 'a';
>>> x == y
True
>>> str(x) == str(y)
False
```

If we're appealing to popular languages, I'd point out that many languages do actually ship ordered maps and aside from the slight performance disadvantage vs. hashing, they are often used and even preferred for the reasons above. Rust's BTreeMap, the ordered maps of Java (TreeMap), C# (SortedDictionary) and C++ (std::map) are all like this, and they are the norm in most functional languages (Haskell, OCaml, etc.) because it's reasonably easy to build a persistent / immutable type of them (eg. a radix trie).

If we want to equip users with a utility type that _overrides_ the normal canonical order and explicitly gives them an insertion order, it's fairly easy to do in the SDK: add a counter to the type and prefix each inserted key with the next counter value. I would very much like this _not_ to be the default map, though.
