### ISSUE TITLE
Auth: Remove nonce functionality from soroban-auth

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#590]
I think we should remove the nonce functionality from soroban-auth.

By bundling nonce validation into the auth interface it feels like we're making the interface handle two unrelated concerns, and that both constrains where the auth interface can be used, and the cognitive load in learning how it works and what it does. That last concern is a pretty big deal because we need developers to understand how auth works, and what it does, and when it is doing multiple things it is harder to understand the subtleties necessary to know if you are using it correctly.

Also, looking at [EIP712](https://eips.ethereum.org/EIPS/eip-712) it is interesting to note that it also explicitly calls out the importance that its scheme does not prevent replay and how it is the applications responsibility to do that.

cc @tamirms @sisuresh @jonjove

---

>+1 What I find most interesting about 712 is two things:
- the domain is very simple and doesn't include a contracts full call stack. Is there anywhere in these sta dards that a full stack shows up?
- the domain includes the verifying contract ID. Afaict this isn't necessarily the receiving contract? Is this accurate?
- the nonce is absent and it is up to the application to prevent replay, which I like and I think it would simplify our auth interface to consider this.

_Originally posted by @leighmcculloch in https://github.com/stellar/rs-soroban-sdk/issues/577#issuecomment-1243923019_

**Comment by leighmcculloch** [comment]
> Removing the nonce would make the single identifier auth scenario more complex for users and more error prone.

I think the complexity of the single identifier case is probably somewhat subjective. In terms of code the developer sees it is approximately the same amount of code. Instead of implementing a `NonceAuth` the developer writes a small amount of code like below. The amount of code to write is about the same. The developer has to do the increment anyway in `NonceAuth`. The only thing the developer has to do that they didn't have to do was the equality check.

The `NonceAuth`'s callback nature introduces complexity that requires the developer to understand everything about how it works anyway. For some people callback complexity may be harder to understand than writing our an increment and equality check themselves.

> If we were to remove the nonce, what should we recommend for replay prevention in our example contracts?

I think we'd recommend something in the form:

```rust
let nonce = env.contract_data().get(DataKey::Nonce(...)).unwrap_or_else(|| Ok(BigInt::zero(&env))).unwrap();
if nonce != expected_nonce {
    panic!("bad nonce");
}
env.contract_data().set(DataKey::Nonce(...), nonce + 1);
```

**Comment by tamirms** [comment]
@sisuresh generally speaking, I would recommend the nonce mechanism. but there are cases where you need to have a different replay mechanism because of the smart contract's use case. An example of that would be limit orders in decentralized exchanges. In that use case, I've seen smart contracts hash the limit order and have a storage mapping of order hash to amount filled:

https://github.com/0xProject/protocol/blob/33e260f9db2795d2ef738c1754a2c396dd5ba1ce/contracts/zero-ex/contracts/src/features/native_orders/NativeOrdersSettlement.sol#L544-L550

https://github.com/1inch/limit-order-protocol/blob/9ccf756d66a258a7150cc78e2a3d733eb40b390b/contracts/OrderMixin.sol#L161-L169

I think that the the smart contract developer should have the flexibility of implementing the replay protection in their own code as you suggested:

> but another option would be to just store the nonce in contract data like we do today, but outside of the auth crate.

Also, another common pattern is to include expiration timestamps / sequence numbers on signatures. As with replay protection, instead of forcing the pattern on the developers, I think it would be better to allow that type of validation to be implemented outside the auth package.

**Comment by tamirms** [comment]
> another option would be to just store the nonce in contract data like we do today, but outside of the auth crate. This is similar to what some solidity contracts do like [compound](https://github.com/compound-finance/comet/blob/f8fc505b8ef9a68a8fbb7c6fbf259dc8a6c95ad6/contracts/CometExt.sol#L213), and would use less storage.

I'm not sure that uses less storage. In the compound example ,the type used to represent a nonce is uint256. A hash has the type of bytes32 which also occupies 256 bits of space

**Comment by sisuresh** [comment]
Ok I agree with you two that should remove the nonce to allow more flexibility with the auth crate. There's still the concern of forgetting to implement replay protection, which is more difficult to do currently because the user needs to implement `NonceAuth`, but the more complex auth scenarios will make nonce management confusing, and could lead to subtle vulnerabilities if we try to force it into the auth crate. @jonjove do you have any concerns about removing replay protection?
