### ISSUE TITLE
Test utils to fetch all keys in a contract's data

### ISSUE THREAD

**Issue by heytdep** [stellar/rs-soroban-sdk#737]
### What problem does your feature solve?
Having a testutil in the SDK to retrieve all keys in a contract's data could ease testing.

(context: https://discord.com/channels/897514728459468821/1033024797153706085/1033055285507543141)

**Comment by graydon** [comment]
Totally reasonable thing to add!

**Comment by leighmcculloch** [comment]
I've implemented this by adding a `.all()` function to each storage type that retrieves not just the keys, but also the values. Because of the way the underlying storage is arranged it is just as easy to do both at the same time as it is to return only the keys.

And from the map returned you can get the keys easy enough:

```rust
env.storage().persistent().all().keys()
```

https://github.com/stellar/rs-soroban-sdk/pull/1118

**Comment by leighmcculloch** [comment]
@heytdep This is been completed and will be included in the next release. I recommend subscribing to the repo for release announcements if you're waiting on this feature going out. Thanks for suggesting it!
