### ISSUE TITLE
Auth Next: Contract IDs use `Address` not `BytesN<32>`

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#868]
This probably should be done after/together with https://github.com/stellar/rs-soroban-env/issues/692 (address conversion host fns)

There are two ways to approach this:

- Host-side: change all the respective host fns to use `Address`
- SDK-side: leave the host as is and use the conversion functions from https://github.com/stellar/rs-soroban-env/issues/692 in SDK to convert from contract `Address` to `BytesN<32>`

**Comment by leighmcculloch** [comment]
Cross posting from Discord: https://discord.com/channels/897514728459468821/1103075731715653672

+100 for us changing all uses of `BytesN<32>` and contract IDs to using `Address`.

If we end up succeeding at true account abstraction, in the end an Address that is a contract ID should be usable anywhere any Address is usable and the importance of contract vs account addresses should fade away even more.

I'd like to see these these places using `Address` instead of `BytesN<32>`:
 ● Contract clients must be instantiated with a BytesN<32>.
 ● Registering contracts in tests returns a BytesN<32>.
 ● Passing around contract IDs between contracts in our examples use BytesN<32>.
 ● Env call stack functions. Possibly it would even make sense to have the source account be a frame in the call stack 🤔.
 
I'm mainly in support of this because by proliferating BytesN<32> about in so many ways, the developer has to learn about and deal with both Address and BytesN<32> and their conversion. When coding myself I find myself doing conversions between them as a matter of necessity and their distinction isn't adding much value to the code I write – it feels like busy work.

It'd especially clean up the testing API. `register_contract` would return an Address, that could immediately be used as an Address to be authorized.

---

In terms of host-side vs sdk-side, I think we should do this host-side. It will result in smaller WASM for the common case where a contract does not need a `BytesN<32>` for the contract ID.

**Comment by leighmcculloch** [comment]
Given that the host-side will be more work, we could do SDK-side earlier using the new conversion functions that were implemented, then update the SDK to be use the host-side when that change is made. Wdyt @dmkozh?

**Comment by dmkozh** [comment]
> we could do SDK-side earlier using the new conversion functions that were implemented, then update the SDK to be use the host-side when that change is made

I think we'd need to do the host side change as well for the release, including some XDR changes. E.g. we might want to use `Address` when deploying contracts in order to make the client code cleaner as well (otherwise the clients would still need to maintain the distinction between the contract ids and `Address` when building txs). I don't have a strong opinion on sequencing though - it seems like this can be done in a reasonably async fashion.
