### ISSUE TITLE
Auth Next: Revisit testing interface

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#875]
Current testing interface might be a bit confusing due to the fact that we provide the auth records for the most recent contract call. We could signify that by chaining the auth check with the contract invocation, for example:

- `client.expect_auth(...).xfer(...)` - specify expected auth entries before invocation. This could be a bit confusing though in case if a contract method fails for a different reason
- `env.record_auth(|| client.xfer(..))` - this explicitly specifies the intent of verifying auth and provides more clear errors (as `assert_eq` should be used on to of this). The downside is that the contract call should happen in the closure.

**Comment by tomerweller** [comment]
For some added context: 
1. When invoking a contract in local-testing mode all `require_auth()` checks automatically succeed and 
2. The successful authorization of the last invocation can be accessed through `env.recorded_top_authorizations()` 

Examples: [Here](https://github.com/stellar/soroban-examples/blob/v0.6.0/auth/src/test.rs#L16:L31) is how this is used in the official auth example. And [here](https://github.com/tomerweller/tinynft/blob/master/src/test.rs#L24:L26) is a more minimal version from my own tinynft implementation

@dmkozh, your proposal seems to tackle the idiosyncratic nature of handling 2 but I think that 1 is also a problem: the idea that all auth checks succeed without providing explicit auth is unintuitive. 

invoker-auth (auth next's predecessor) required explicit authorization using `client.with_source_account()` ([see previous auth example](https://github.com/stellar/soroban-examples/blob/71c07f0f40f4b06100df6971df0d03d003ce9877/auth/src/test.rs#LL16C37-L16C37)), which I found to be more intuitive. 


### Alternative proposal 

For auth next I propose that authorizations won't automatically succeed and will be provided explicitly, similar to how invoker auth used to work. Practically this could looks something like these three versions:

``` rust
//authorization is forced to succeed  
assert_eq!(client.with_auth_success().increment(&user_2, &4), 5);

//authorization is explicitly provided, checks only pass if there's a match
let user1_auth = std::vec![(
    user_1.clone(),
    contract_id.clone(),
    symbol!("increment"),
    (user_1.clone(), 5_u32).into_val(&env)
)];
assert_eq!(client.with_auth(user1_auth), increment(&user_1, &5), 7);

//authorization is checked against a list of Addresses (for brevity)  
assert_eq!(client.with_auth_accounts([&user_1]), increment(&user_1, &5), 7);
```

Some previous discussion on discord [here](https://discord.com/channels/897514728459468821/1078007735616016515/1078007735616016515).

**Comment by paulbellamy** [comment]
I'd say the first option (`expect_auth`) only allows full exact match (without some sort of matcher system), while the closure allows people writing tests to check specific parts of the auth are what they expect (e.g. `assert!(call_stack.includes("some_method"))`), which may be more intuitive.

Building on tomer's suggestion, instead of adding a `client.with_auth()` method, I was going to suggest maybe we could pass the signers as arguments wherever the client would take an Address. However we also need to support the "additional signers" workflow (as well as setting the txn source account). So maybe a middle-ground:
```rs
let user1_key = Keypair::full(/* ... */);
let user2_key = Keypair::full(/* ... */);
client
  .with_signers(user1_key, user2_key)
  .increment(&user1_addr, &5);
```
Then those keys are automatically used to sign whatever call-stacks etc are needed. If you want to test auth failing, you could omit the relevant signer.

Adds a bit of magic to save the faff of explicitly building auth vectors or signing call-stacks. But maybe a less "magic" option which allows the test-writer to expose some of the machinery would be more useful. 🤔 

@dmkozh, for more realistic testing of invoker-style auth, do we also need a way to set the txn source account?

**Comment by dmkozh** [comment]
> instead of adding a client.with_auth() method, I was going to suggest maybe we could pass the signers as arguments wherever the client would take an Address. 

This is exactly what I wanted to avoid and it really doesn't make any sense to do any actual signing in the tests (the auth testing has been really, really messy due to the need to do the signing). We would just add a bunch of random signatures to the invocation here instead of actually checking the part that matters (the addresses for which we require authorization and the respective call args).

> Adds a bit of magic to save the faff of explicitly building auth vectors or signing call-stacks.

You don't have to build these at all now. But if you want to cover auth, you can check the payloads. The intent is to not do that check on every invocation, because besides auth you may want to focus on another aspects of the business logic.

> for more realistic testing of invoker-style auth, do we also need a way to set the txn source account?

Invoker auth is completely transparent for the contract and there is really no need to cover it specially in the tests.

I think there still seems to be some disconnect of the expectations here. With the way things work currently (heavily leaning on the host in multiple aspects), we can benefit from declarative testing of `require_auth` which I think is way better than injection/mock-style testing:

- It is optional - there is no need to setup every call and write wrappers for every contract function to just generate some boilerplate. I've written quite a few tests with non-optional auth for host and it is pretty time-consuming and daunting. But we can avoid that now in all the user contracts.
- It is comprehensive - the single payload you're verifying is necessary and sufficient to make your contract call pass. There is no need for any negative testing. Again, writing the tests that need to cover negative cases is both less comprehensive (because you can't cover every negative case) and more verbose (because you still would write at least a few negative cases).

I want to emphasize again, that the auth failure testing is not necessary. We guarantee that the contract will trap. Auth exists *outside* of the contract call, similar to the footprint, fees, metering data etc. There is no good reason to test what happens when you run out of budget or access an unknown entry. The same way there is no need to test mismatching signature or signature payload.

I realize that the current testing interface may not be very intuitive, which is what I'm trying to address with this issue. But I really don't see a good reason for changing the approach - everything seems to be more complicated for both contract developers and for the host implementation, while not providing a significant benefit (besides the ability to cover failure scenarios that are already covered by the host tests, which is not something I'd want to see).

**Comment by paulbellamy** [comment]
> We guarantee that the contract will trap.

So long as the contract writer has used the auth correctly.

> There is no good reason to test what happens when you run out of budget or access an unknown entry.

run-out-of-budget I agree on, but access to uknown entry seems like it might involve contract logic (to handle a missing storage data), which you would want to test.

---

But generally I agree, yeah. You shouldn't really need negative auth testing, unless you're doing more interesting auth stuff maybe...

**Comment by paulbellamy** [comment]
I agree with all that. Saying you shouldn't need to do negative testing for auth makes sense, unless you're doing something more "interesting". But a test for "only the admin can do action X" Seems like a pretty sensible thing to want to verify.

> We guarantee that the contract will trap.

Assuming the contract author has correctly called the auth machinery.

> There is no good reason to test what happens when you run out of budget or access an unknown entry.

Agree re: out-of-budget. But access an unknown storage entry seems pretty reasonable to test if you're doing contract logic to handle a missing storage entry.

**Comment by dmkozh** [comment]
>t access to uknown entry seems like it might involve contract logic (to handle a missing storage data), which you would want to test.

I mean the entry missing from the footprint, not from the storage in general. Basically this is a pre-requisite for the contract invocation to succeed and it's passed as a 'side input' of the contract invocation. Footprint, budget data, fees and auth/signatures are similar in this sense (again, I recognize that auth is trickier because it is somewhat more customizable; but that doesn't change the fact that it is a side input and effectively a precondition).


> Assuming the contract author has correctly called the auth machinery.

Incorrect calls would be caught by `recorded_top_authorizations` or whatever new test interface. FWIW if we're concerned about the users forgetting to cover this at all, we still could go the 'post-check' route instead of imitating the contract failure (e.g. add a check like `if !recorded_top_authorizations.is_empty() { panic!(...); }`) and then add a blanket way to disable that (like `with_auth_success()` that Tomer has suggested). That would make tests more verbose, but at least wouldn't require adding the expected payloads to every call. What I really want to avoid is injecting the failure conditions that aren't really meaningful for the contract as there is no contract logic to handle them.

> unless you're doing something more "interesting". 

I wonder what that would be. With the current API there is no way to handle the auth failures gracefully. We could add that, but I've yet to see a strong use case for that. So far the only somewhat legitimate case would be to get a bunch of addresses from storage and require auth for a fraction of them. But that would be hard to preflight and sign correctly, so probably a better solution is to just pass the addresses explicitly in such case. This applies to the failure scenarios in general - if they're ever meaningful, then preflight becomes hard to use (as your preflight call has to be supplied with mock auth failures) and the surface of potential errors/vulnerabilities grows significantly. Basically if there is no hard requirement to authorize some address, it's better to handle that in a contract-specific way (like don't pass the address/pass a flag/store a parameter in storage etc.) rather then relying on `require_auth` error handling (that can fail in multiple ways that contract can't know about).

**Comment by tomerweller** [comment]
> I want to emphasize again, that the auth failure testing is not necessary

This argument keeps surfacing and either I don't understand it or, from my perspective, is only partially true. I agree that the auth framework doesn't need to be tested. However,  access control (or lack thereof) _does_ need to be tested.

Which leads me to what I think might be another issue with always-success auth: it forces you to write tests that cover no-auth scenarios. If a contract invocation that _doesn't_ require auth is successful the developer would need to explicitly examine that no authorization was performed. 

[This example](https://github.com/tomerweller/tinynft/blob/0dee228af0185297642759491bd58d9418cd7b77/src/test.rs#L22) (again from my tinynft contract) demonstrates that. I am forced to test that no authorization is required to initialize the nft because maybe I accidentally required auth and always-successful auth made it work.

**Comment by dmkozh** [comment]
> . However, access control (or lack thereof) does need to be tested.

What exactly do you mean by access control here? If your function has to be authorized by the admin, then you can verify that fact (currently via `recorded_top_authorizations`). This is more declarative approach - instead of checking whether the function fails when there is no admin signature, you check that the function requires admin access. I'm not sure if there is another scenario that I'm missing here.

>  it forces you to write tests that cover no-auth scenarios

We actually don't force anything, you're free to skip all these checks (and I'd argue it's enough to do them once, unless you anticipate some complex logic). We do provide the tool to verify these scenarios indeed. I suppose, the alternative is to force users to explicitly specify `require_auth` calls ahead of time, which is definitely much more typing and thinking than just doing the check once. Again, from the UX standpoint probably something like `client.expect_no_auth().balance(..)` would look nicer (but `expect_no_auth` also should be optional; there is really no need to type it every time you want to check balance).


>  I am forced to test that no authorization is required to initialize the nft because maybe I accidentally required auth and always-successful auth made it work.

Besides the point that you're not forced to do so, I don't really see why this is a bad thing. This is something you probably want to cover in the tests, one way or another.

**Comment by leighmcculloch** [comment]
I've been playing around with the auth functionality and the thing that stands out to me is that it is difficult in tests to learn how auth works. Instead of learning how auth works, the framework has me focused on understanding in what ways auth doesn't work in the test framework.

All auths succeeding by default is disorienting, and results in tests that don't tell a story that includes auth. Contract tests should tell a story about how a contract works, and auth is part of that. 

What we have by default is akin to a preinstalled stub that lets every auth succeed, but that stub is invisible to the developer.

I think it would be intuitive, and educational, if the default behavior regarding auth was for real auth behavior to be enforced. The SDK would then provide functions for setting up success-stubs for auth that a developer can use to get auth to succeed magically if they don't want to setup signatures or account contracts. This provides approximately the same "ease of use" as what we have right now, but it shifts the knowledge from the invisible to the visible and causes tests to tell a story about their auth. It also have the test environment work just like the network until those stubs are explicitly engaged, which feels more genuine.

I'm suggesting we add functions like this:

```rust
// Call balance as if Address has successfully auth'd with all args.
client.auth(Address).balance(..);
```
```rust
// Call balance as if Address has successfully auth'd with the given args.
client.auth_with_args(Address, args).balance(..);
```

This interface is similar to the one that @tomerweller posted above. It moves auth into the "arrange" part of the "arrange/act/assert" story that @paulbellamy mentions above, which I think is relatively important in telling a natural time ordered story about how invocations of contracts work, and for forcing developers/us to think about and make auth explicit. It also has the test focus its assertions on the outcomes rather than contract internals.

It's common in some stub/mock testing frameworks for stubs to "have to be used/consumed", and I think that behavior would be very suitable here. In essence I think there's value in having the above two functions expect those auths to take place, and if they don't, that'd be an error. @paulbellamy I realize this causes an assertion to be defined in the arrange step, but this is more about having a safety that ensures that the arrange step is accurate and complete than it is about being an assertion of the test. I think the assertions at the end of the test should be focused on the contract function's non-auth functionality, which should fail if auth failed since auth gates that functionality.

**Comment by dmkozh** [comment]
So basically you suggest building a mocking framework here. That's an option I've considered as well, but it is not trivial to implement, as there is a number of features that should be there:
- Some default permissive modes
- Wildcards/matches to skip uninteresting args
- Modes (strict/non-strict to regulate whether the calls have already been consumed)
- Extensibility for validating the whole trees in the consistent fashion, with all the matcher and wildcard support (the current solution can be relatively easily extended to support the trees)
- A whole new host-side auth mode, that is neither enforcing nor recording (as to support the framework)
- Additional code generation for the new client methods (that's the general issue with any approach involving adding the call modes to client)

I suppose this would provide some benefits, like looking more familiar to some contract writers (though I haven't seen much mock usage in Rust in general, so not sure how common they are). But there are downsides as well:
- This approach suggests that you should also be testing the negative scenarios. That's not actually the case, as there is no objective value in these negative scenarios.
- The additional boilerplate for every contract function call is annoying and will either cause writing more verbose tests or to create wrappers for every contract function, which was one of the things I really wanted to avoid with the new auth approach

From my own experience with various rpc mocks, they're not the simplest things to use and even with the powerful framework it's sometimes really annoying to setup the tests correctly. I wouldn't really want to spend weeks on building something that is only marginally better (if at all) than the current approach. I'm curious though if you see some simple way of implementing this that is also scalable/extensible enough.

**Comment by dmkozh** [comment]
The examples are lightweight because they omit the necessary info (contract id, function name, multiple addresses).  I would be curious to see how something like [this](https://github.com/stellar/soroban-examples/blob/main/atomic_multiswap/src/test.rs#L91) would look like. Notice, that the contract id is different from the top-level contract id and also that we use `asset_eq_unordered` for matching. Of course, we can have multiple functions with different signatures (not sure if that's fitting into philosophy of providing a single way of doing things though). The current solution at least allows testing arbitrarily complex auth flows (the tree testing is lacking, but not not impossible and it's also possible to provide a similar function to support the whole tree matching).

I also would like to resolve another points I've mentioned. I really would like to avoid having another, testing-only, auth mode. We could maybe reuse the recording mode, but change the way the expectations are set. That still runs into flexibility/boilerplate issues though.

**Comment by leighmcculloch** [comment]
Closing due to #929. This will be an ongoing story, but I think we addressed the core so far, and we can create new issues as new information arises or reopen if we discover it is fundamentally not improved.
