### ISSUE TITLE
Auth Next: Support enforced auth and real auth in tests

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-soroban-sdk#917]
Independent of #875 which is discussing a convenient test specific interface for working with auth, we need to allow support for using auth in its rawest form in the SDK tests, where enforcing is enabled and the same tools are available as will be available outside of tests.

While it's critical that we provide a simple interface for mocking, stubbing, or testing against auth without actually performing auth (the topic of #875), we also need to provide a way for developer to play with custom accounts in enforcing mode, where the actual contracts execute, and where developers can explore much like a playground the full scope of how auth works on a real network.

A goal of the test framework in the SDK is that to the largest extent possible it operates just like a contract will experience on the real network. In many ways it is a playground that lets a user discover and learn about Soroban, and auth is a big component of that.

Adding this capability should interact very little with whatever we plan to do in #875 because running in enforcing mode should just be a matter of not enabling the mocks/stubs/conveniences that #875 provides.

**Comment by dmkozh** [comment]
While I'm not strictly opposed to this in concept, there is a few things to keep in mind:

- the enforcing mode requires passing the `ContractAuth` payloads to the host. these payloads have to have the call trees of `require_auth`
- it also requires the correct accounting of nonces (though this might be simplified with temp storage nonces, https://github.com/stellar/rs-soroban-env/issues/655
- it requires the ledger state for the account, classic or custom, depending on what we want to cover here. the ledger state for the accounts would also result in additional ledger state required for SAC
- it requires the proper signatures

Keeping all these requirements in mind, I think the best way to cover this is to do that via sending transactions to the core, i.e. that would be an integration test (as in 'integration between dapp and stellar', not 'integration between contracts'). If we strive to emulate the real behavior and use the state external to the control invocation (such as the auth payload/sigantures/nonces), we should probably also take the footprints and resource consumption into account as well. This way the developers will be able to actually test the wallet interactions, auth payload building, footprint building etc.

I'm not sure about building this into the SDK directly though. It would still need to emulate a big chunk of the logic (unless we want the users to write boilerplate for the sake of boilerplate), while not providing any additional coverage. E.g. if we have a custom, SDK-implemented builder of the auth payloads, then it will be only usable by the SDK tests for the SDK tests. It doesn't help any real use case (as in reality XDR will have to be used) and it doesn't cover anything (because auth payloads are managed outside of the SDK).
